name: Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install setuptools
          pip3 install makelove

      - name: Build
        run: makelove --config build_config.toml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: bin/
